Traceback (most recent call last):
  File "mygame.py", line 13, in <module>
  File "E:\2d\snowfight .1\game_framework.py", line 87, in run
    start_state.enter()
  File "E:\2d\snowfight .1\start_state.py", line 14, in enter
    image = load_image('image\\title.png')
  File "C:\Python34\lib\site-packages\pico2d.py", line 272, in load_image
    raise IOError
OSError
Traceback (most recent call last):
  File "mygame.py", line 13, in <module>
  File "E:\2d\snowfight .1\game_framework.py", line 87, in run
    start_state.enter()
  File "E:\2d\snowfight .1\start_state.py", line 14, in enter
    image = load_image('image\\title.png')
  File "C:\Python34\lib\site-packages\pico2d.py", line 272, in load_image
    raise IOError
OSError
Traceback (most recent call last):
  File "mygame.py", line 13, in <module>
  File "E:\2d\snowfight .1\game_framework.py", line 87, in run
    start_state.enter()
  File "E:\2d\snowfight .1\start_state.py", line 14, in enter
    image = load_image('image\\title.png')
  File "C:\Python34\lib\site-packages\pico2d.py", line 272, in load_image
    raise IOError
OSError
